# Generated by Django 3.1.4 on 2020-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='Логин')),
                ('user_firstname', models.TextField(max_length=30, verbose_name='Имя')),
                ('user_lastname', models.TextField(max_length=30, verbose_name='Фамилия')),
                ('id_user', models.CharField(max_length=10, verbose_name='id_user')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
