# Generated by Django 3.1.4 on 2020-12-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.CharField(max_length=10, verbose_name='tg_id'),
        ),
    ]
