# Generated by Django 3.1.6 on 2021-05-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201229_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_name',
            field=models.CharField(default=0, max_length=30, verbose_name='Bot Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_username',
            field=models.CharField(default=0, max_length=30, verbose_name='Bot Username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='global_id',
            field=models.CharField(default=0, max_length=30, verbose_name='Global id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='pID',
            field=models.IntegerField(default=0, verbose_name='pID'),
        ),
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bot',
            name='token',
            field=models.CharField(default=0, max_length=100, verbose_name='Token'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('date', models.CharField(max_length=30, verbose_name='Date')),
                ('bot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bot')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='CustomCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default=0, max_length=100, verbose_name='Команда')),
                ('response', models.CharField(default=0, max_length=500, verbose_name='Ответ')),
                ('bot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bot')),
            ],
            options={
                'verbose_name': 'Пользовательские команды',
                'verbose_name_plural': 'Пользовательская команда',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('first_name', models.TextField(max_length=30, verbose_name='Имя')),
                ('last_name', models.TextField(max_length=30, verbose_name='Фамилия')),
                ('tg_id', models.CharField(max_length=10, verbose_name='Id telegram')),
                ('pathAvatar', models.CharField(max_length=200, verbose_name='Avatar Path ')),
                ('dateReg', models.CharField(max_length=200, verbose_name='Дата регистрации')),
                ('bot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bot')),
            ],
            options={
                'verbose_name': 'Пользователь Бота',
                'verbose_name_plural': 'Пользователи Бота',
            },
        ),
    ]
